2019-04-05 16:05:08,093 ERROR: Exception on /Download [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 212, in enterprise
    return render_template('Download/enterprise.html')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\Download\enterprise.html", line 1, in top-level template code
    {% extends 'base.html' %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2019-04-05 16:05:08,133 ERROR: Exception on /Download [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 212, in enterprise
    return render_template('Download/enterprise.html')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\Download\enterprise.html", line 1, in top-level template code
    {% extends 'base.html' %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2019-04-05 16:05:08,136 ERROR: Exception on /Download [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 212, in enterprise
    return render_template('Download/enterprise.html')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\Download\enterprise.html", line 1, in top-level template code
    {% extends 'base.html' %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2019-04-05 16:05:08,454 ERROR: Exception on /Download [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 212, in enterprise
    return render_template('Download/enterprise.html')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\Download\enterprise.html", line 1, in top-level template code
    {% extends 'base.html' %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
